name: CI
on: 
  push:
    branches: 
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.3.1
    - run: npm ci
    - run: npm install vuepress
    - run: npm run build
    - run: cp CNAME docs/.vuepress/dist/
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@3.5.9
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.VUEPRESS_BLOG_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: docs/.vuepress/dist
